---
- name: Converge
  become: true
  hosts: all
  post_tasks:
    - name: Verify Ruby is installed.
      changed_when: false
      ansible.builtin.command: ruby --version
  pre_tasks:
    - ansible.builtin.apt: update_cache=true cache_valid_time=600
      name: Update apt cache.
      when: ansible_os_family == 'Debian'
    - name: Add rubygems bin dir to system-wide $PATH.
      ansible.builtin.copy:
        content: PATH=$PATH:{{ ruby_gems_bin_path }}
        dest: /etc/profile.d/ruby.sh
        mode: "0644"
    - name: Don't install Bundler on CentOS 7 because of old Ruby version.
      ansible.builtin.set_fact:
        ruby_install_bundler: false
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'
  roles:
    - role: buluma.bootstrap
    - role: buluma.ruby_gems
  vars:
    ruby_gems_bin_path: /root/.gem/ruby/bin
    ruby_install_gems:
      - json
    ruby_install_gems_user: root
