---
- name: Converge
  become: true
  hosts: all
  post_tasks:
    - name: Verify Ruby is installed.
      changed_when: false
      ansible.builtin.command: ruby --version
  pre_tasks:
    - ansible.builtin.apt: update_cache=true cache_valid_time=600
      name: Update apt cache.
      when: ansible_os_family == 'Debian'
  roles:
    - role: buluma.ruby_gems
  vars:
    ruby_install_from_source: true
    ruby_install_gems:
      - sass
    ruby_install_gems_user: root
